# google認証機能
development:
  secret_key_base: XXXXXXXXXXXXXXXXX
  google_client_id: 940117482387-sl3p3quvl1ccgfl2jcpk9htr5ti6mi5r.apps.googleusercontent.com
  google_client_secret: WORWovZ9FaTk5eXRJT3D41NJ
